# SecureSockets document generator jazzy settings

copyright: Copyright 2016-2017 Rien van der Lugt
author: Rien van der Lugt
module: SecureSockets
hide_documentation_coverage: true
xcodebuild_arguments: [-target, SecureSockets]
github_url: https://github.com/Balancingrock/SecureSockets
output: ~/Documents/Websites/swiftfire-website/projects/securesockets/reference
clean: true
theme: fullwidth
